GET http://localhost:8082

###

GET http://localhost:8082/get

###

GET http://localhost:8082/get/1

###

GET http://localhost:8082/get/1001

###

POST http://localhost:8082/create
Content-Type: application/json; charset=utf-8
Accept: application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8

{
    "id": 1001,
    "station": "Mühlenberg Loch",
    "longitude": 9.7978,
    "latitude": 53.5484
}

###

PUT http://localhost:8082/update
Content-Type: application/json; charset=utf-8
Accept: application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8

{
    "id": 1001,
    "station": "Mühlenberger Loch",
    "longitude": 9.7978,
    "latitude": 53.5484
}

###

DELETE http://localhost:8082/delete
Content-Type: application/json; charset=utf-8
Accept: application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8

{
    "id": 1001
}
